baseurl = "https://giseldo.github.io"
DefaultContentLanguage = "br"
title = "IA com GN"
theme = "beautifulhugo"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[Services]
  [Services.Disqus]
    Shortname = "giseldo"
    shortname = "giseldo"
  [Services.googleAnalytics]
    id = "G-GFJR491N4J"

[Params]
  homeTitle = "Inteligência Artificial" 
  subtitle = "com Giseldo Neo"
  # logo = "img/avatar-icon.png" 
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = false
  showRelatedPosts = true

[Params.author]
  name = "Giseldo Neo"
  website = "giseldo.github.io"
  email = "giseldo@gmail.com"
  github = "giseldo"
  twitter = "giseldoneo"
  linkedin = "giseldo-neo-65b252b"
  instagram = "neogiseldo"
  youtube = "user/giseldoneo"
  kaggle = "giseldo"
  discord = "https://discord.gg/NTdaT2Uf37"

[[menu.main]]
    name = "Blog (↗)"
    url = "http://giseldo.hashnode.dev/"
    weight = 1

[[menu.main]]
    name = "Cursos (↗)"
    url = "http://giseldo.github.io/cursos/"
    weight = 2

[[menu.main]]
    name = "Youtube (↗)"
    url = "http://youtube.com/giseldoneo"
    weight = 3

